### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by GugaS1lva** [kellysondias/desafio-3-js-intermediario#1]
Bixei teu repo e adicionei dois links em baixo das imagens, vê se curtiu:
![Screenshot_47](https://user-images.githubusercontent.com/92289607/170218961-265d58e0-1c06-4172-b2ba-4019ba559b0e.png)

Ficou bonitinho aqui pra mim, é só uma sugestão. tmj👌🏻

**Comment by kellysondias** [comment]
Gostei! Se pá fica melhor pras pessoas acharem o link pra página. Valeus!
